### ISSUE TITLE
Virtualmin generates syntax error in DMARC records (tag order matters)

### ISSUE THREAD

**Issue by chris001** [virtualmin/virtualmin-gpl#117]
BUG: Virtualmin's generator for DMARC record creates a bad syntax which is failing validation:
https://www.dmarcanalyzer.com/dmarc/dmarc-record-check/

Results:

**DNS record**

`v=DMARC1; pct=50; ruf=mailto:postmaster@myvirtualmin.com; rua=mailto:postmaster@myvirtualmin.com; p=quarantine`

**Problems**

We've noticed the following problems with your DMARC records .
Info : **_The tag "`p=`" should appear directly after "`v=`".**

Correct syntax:
`v=DMARC1; p=quarantine; pct=50; ruf=mailto:postmaster@myvirtualmin.com; rua=mailto:postmaster@myvirtualmin.com`

The correct syntax verifies, it passes DMARC record validation.

**Comment by jcameron** [comment]
This should be fixed already in Virtualmin 6.08 (for newly generated records)

**Comment by chris001** [comment]
> This should be fixed already in Virtualmin 6.08 (for newly generated records)

Unfortuantely, on Virtualmin 6.08, when you edit existing DMARC settings (under Server Configuration / DNS Options / edit "Percentage of messages to apply policy" to 100 / Save / get Save confirmation), the bug still exists, Virtualmin updates the DMARC record into the DNS zone, (which was previously manually edited to have the correct parameter order and correct syntax), Virtualmin updates the DMARC record with the wrong parameter order, wrong syntax, and DMARC fails validation again for this domain, as soon as the zone version with the DMARC record with the bad syntax, propagates throughout the internet. :(

**Comment by jcameron** [comment]
Apologies, turns out that there were multiple implementations of the DMARC joining code in Virtualmin, and only one was fixed :-(   The next Webmin release will fix the other one.

**Comment by mruepp** [comment]
Any option to regenerate the dmarc syntax on all of the virtual servers? I have the same problem.

**Comment by chris001** [comment]
> 
> 
> Any option to regenerate the dmarc syntax on all of the virtual servers? I have the same problem.

It'd be nice if the "Validate Virtual Servers" would scan each domain for bad `DMARC` record syntax, and when bad syntax is detected, offer to update/fix it.

**Comment by jcameron** [comment]
You could force re-generating of the DMARC records to the default for all domains with a shell script like :

<code>
for dom in `virtualmin list-domains --mail --dns --name-only`; do
  virtualmin modify-dns --domain $dom --no-dmarc
  virtualmin modify-dns --domain $dom --dmarc
done
</code>

**Comment by shoulders** [comment]
@chris001 have these various issues been fixed with the patches above?

**Comment by chris001** [comment]
> @chris001 have these various issues been fixed with the patches above?

Yes, DMARC is fixed and working now, I'll close this issue!
Note: to verify for yourself whether DMARC is working and syntax correct on your virtualmin/webmin, [this mxtoolbox online tool](https://mxtoolbox.com/dmarc.aspx) is good, it provides a detailed analysis of the DMARC record.
