### ISSUE TITLE
Virtualmin Validation Failed: "unexpected server 'php-fpm: pool"

### ISSUE THREAD

**Issue by Francewhoa** [virtualmin/virtualmin-gpl#227]
## Steps to Reproduce

1. Using:

     * Virtualmin 6.14
     * Webmin 1.962
     * Debian 10 Buster
     * Apache 2.4.38

2. Using Virtualmin, configure multiple Top Virtual Servers to use various version of PHP-FPM. Such as `5.6.*` and `7.2.*`. Packages come from:

     * From https://deb.sury.org
     * Ticket https://github.com/oerdnj/deb.sury.org/

3. Using Virtualmin, navigate to "**Limits and Validation**" vertical tab, "**Validate Virtual Servers**" sub-vertical tab, "**Validate Now**" horizontal tab

   1. Click on the "**Valide** Now" button

   1. All Virtual Server validate.

4. Do not do any configuration change

5. Update PHP-FPM packages the present latest versions listed below. In this example, this was done on November 5th, 2020:

      * PHP-FPM 5.6.40
      * PHP-FPM 7.0.33
      * PHP-FPM 7.1.33
      * PHP-FPM 7.2.34
      * PHP-FPM 7.3.19
      * PHP-FPM 7.4.12

6. Do not do any configuration change

7. Using Virtualmin, navigate to "**Limits and Validation**" vertical tab, "**Validate Virtual Servers**" sub-vertical tab, "**Validate Now**" horizontal tab

   1. Click on the "**Valide Now**" button

   1. Virtualmin return this message. Via email notification.

```
Virtualmin Validation Failed

Virtual server validation
-------------------------

domain-1.ca
Administration user : Port 8002 is being used by <USER.1> to run unexpected server 'php-fpm: pool <DIGIT.NUMBER.1>'

domain-2.ca
Administration user : Port 8001 is being used by <USER.2> to run unexpected server 'php-fpm: pool <DIGIT.NUMBER.2>', 
Port 8001 is being used by <USER.2> to run unexpected server 'php-fpm: pool <DIGIT.NUMBER.2>'

domain-3.ca
Administration user : Port 8000 is being used by <USER.3> to run unexpected server 'php-fpm: pool <DIGIT.NUMBER.3>'
```

8. This challenge started on November 5th, 2020. After the upgrade to PHP-FPM version 5.6.40.

9. Expected result is that all Virtual Server would validate. No error message are return.

Any volunteer for a patch? The Ubertus team would be happy to contribute testing.

# What We Tried But Did Not Work

1. "Re-Check Configuration" WITHOUT server reboot. See output in this comment https://github.com/virtualmin/virtualmin-gpl/issues/227#issuecomment-790273080
2. "Re-Check Configuration" WITH server reboot. See output in this comment https://github.com/virtualmin/virtualmin-gpl/issues/227#issuecomment-790273080

# Possible Cause

The cause of this challenge is not known. The following are just speculations.

* Maybe a Port collision problem? Port 8000, 8001, 8002.
* Maybe PHP-FPM fails to detect ports in use? https://github.com/webmin/webmin/issues/518 
* Maybe Virtualmin, somehow change PHP-FPM ports without asking or without notifying anyone?
* https://www.virtualmin.com/node/66956 
* https://virtualmin.com/comment/815162#comment-815162 
* https://virtualmin.com/comment/814989#comment-814989 
* https://virtualmin.com/comment/814989#comment-814989 
* https://virtualmin.com/comment/815376#comment-815376 
* https://www.virtualmin.com/comment/818339#comment-818339

**Comment by abclution** [comment]
> Maybe a Port collision problem? Port 8000, 8001, 8002.

I had this problem also occur after switching site from older versions of PHP-FPM to newer versions.
Virtualmin did not automatically resolve this issue, I had to edit my php pool configuration files manually to choose free ports.

It did not happen again once I resolved it once for each problem domain manually.

**Comment by Francewhoa** [comment]
Thanks for your reply @abclution :) We'll try this. That would be an easy fix.

In the case of our challenge we have not switch PHP-FPM versions. I mean they remain the same versions for months. Then this challenge happened.

**Comment by iliarostovtsev** [comment]
> Virtualmin did not automatically resolve this issue, I had to edit my php pool configuration files manually to choose free ports.

Have you tried re-running configuration check, as this is where FPM ports collisions are fixed?

**Comment by abclution** [comment]
> > Virtualmin did not automatically resolve this issue, I had to edit my php pool configuration files manually to choose free ports.
> 
> Have you tried re-running configuration check, as this is where FPM ports collisions are fixed?

Yes a bunch of times. It played coy and didn't attempt to fix it, even though it detected it splendidly each time.
This was about 3 months ago if I recall.

**Comment by jcameron** [comment]
Thanks - a config check is needed to fix this

**Comment by Francewhoa** [comment]
Thanks for your answers @iliarostovtsev and @jcameron :) We'll try this. That would also be an easy fix.

I will share our result here

**Comment by Francewhoa** [comment]
Hi @abclution , @jcameron , @iliarostovtsev :) Thanks again for your suggestion about re-running configuration check. We happily tried this but this did not resolve this challenge.

Below is the same message as above. But with details if you're interested in those

## Re-Check Configuration

I'm assuming that by `Re-Running Configuration Check` you meant `Re-Check Configuration`. Which is located at "Virtualmin" ---> "System Settings" ---> "Re-Check Configuration" with URL `/virtual-server/check.cgi`

I'm assuming that you did not meant the `Re-Run Configuration`. Which is on another page. Right?  `Re-Run Configuration` is also known as `Post-Installation Wizard`.


## What we tried that did not resolve this challenge

1. "Re-Check Configuration" WITHOUT server reboot
2. "Re-Check Configuration" WITH server reboot

The "Validate Virtual Servers" return this same error message "unexpected server 'php-fpm: pool" Details and steps to reproduce this is in this ticket body above

## "Re-Check Configuration" Output

> Checking Configuration
> 
> The status of your system is being checked to ensure that all enabled features are available, that the mail server is properly configured, and that quotas are active ..
> 
> Your system has <MASKED> GiB of memory, which is at or above the Virtualmin recommended minimum of 256 MiB.
> 
> BIND DNS server is installed, and the system is configured to use it.
> 
> Mail server Postfix is installed and configured.
> 
> Postfix can support per-domain outgoing IP addresses, but is not currently configured to do so. This can be setup in the Postfix Mailserver module.
> 
> Apache is installed.
> 
> The following PHP versions are available : 5.6.40 (/bin/php-cgi5.6), 7.0.33 (/bin/php-cgi7.0), 7.1.33 (/bin/php-cgi7.1), 7.2.34 (/bin/php-cgi7.2), 7.3.27 (/bin/php-cgi7.3), 7.4.15 (/bin/php-cgi7.4), 8.0.2 (/bin/php-cgi8.0), 5.6 (mod_php)
> 
> The following PHP execution modes are available : mod_php cgi fcgid fpm
> 
> The following PHP-FPM versions are available on this system : 5.6.40 (php5.6-fpm) 7.0.33 (php7.0-fpm) 7.1.33 (php7.1-fpm) 7.2.34 (php7.2-fpm) 7.3.19 (php7.3-fpm) 7.4.15 (php7.4-fpm) 8.0.2 (php8.0-fpm)
> 
> Webalizer is installed.
> 
> Apache is configured to host SSL websites.
> 
> MariaDB 10.3.27 is installed and running.
> 
> ProFTPD is installed.
> 
> Logrotate is installed.
> 
> SpamAssassin and Procmail are installed and configured for use.
> 
> ClamAV is installed and assumed to be running.
> 
> Plugin AWstats reporting is installed OK.
> 
> Plugin DAV Login is installed OK.
> 
> Plugin Protected web directories is installed OK.
> 
> Using network interface eth0 for virtual IPs.
> 
> Default IPv4 address for virtual servers is <MASKED>.
> 
> Both user and group quotas are enabled for home and email directories.
> 
> All commands needed to create and restore backups are installed.
> 
> The selected package management and update systems are installed OK.
> 
> Chroot jails are available on this system
> 
> .. your system is ready for use by Virtualmin.

**Comment by Francewhoa** [comment]
This is to confirm that this challenge is still present with the latest version of Virtualmin available for Debian 10 Buster

* Virtualmin 6.14
* Webmin 1.962
* Debian 10 Buster
* Apache 2.4.38

I updated this ticket description accordingly

**Comment by marclaporte** [comment]
@Francewhoa @abclution 

I volunteer for a patch if this issue is still present on the current stable Virtualmin (7.5 as of now)

Thanks!

**Comment by jcameron** [comment]
@marclaporte this should have been fixed a long time ago. Are you still seeing the issue?

**Comment by marclaporte** [comment]
No, I don't see this error message in my usage, but I didn't try the steps described.

My interest is in making sure the configuration check is robust, and it seemed to be a well documented and reproducible issue so worthy of handling/closing. I was hoping for a retest to confirm all is well and we can close.

**Comment by Francewhoa** [comment]
>I volunteer for a patch if this issue is still present on the current stable Virtualmin (7.5 as of now)

Thanks for your offer, Marc. Appreciated and noted. I'll reply as soon as I'm free.

**Comment by iliajie** [comment]
Thanks for the heads-up. This particular issue has been fixed a long time ago.
