### ISSUE TITLE
Restore of domain from server1 to server2 duplicates dns entries with server2 ip instead of replacing. Reset features dns properly sets dns to server2 ip and removes  server 1 ips 

### ISSUE THREAD

**Issue by abclution** [virtualmin/virtualmin-gpl#491]
Webmin version 2.001 
Usermin version  1.860
Virtualmin version 7.3-1 Debian

Hello guys, long time no talk, been over in python land dealing with some things.

Encountering an issue where I am trying to move some domains from one server to another, which I have done many times before.
For some reason, I do not know when this started (been away from virtualmin stuff for almost a year!) restoring a domain from server1 to server2 or the reverse, the DNS/bind entries of server1 do not get replaced with server2 ips, instead new additional entries are made with the ips of server2. This is for all the standard m.* , autoconfig.*, mail.* etc etc. The reverse also happens going from server2 -> server1 as well as doing via the transfer domain (which makes sense as it uses the backup system.)

If on the transferred domain, I run the reset features (and include deleting data) for DNS, the correct entries are written and the old server entries are removed. 

I'm feeling a bit rusty with virtualmin stuff so I am not sure if its me or a bug.

**Comment by jcameron** [comment]
This sounds like a bug! When you do a transfer like this, does the domain already exist on the destination system? Or is it being created as part of the transfer process?

**Comment by abclution** [comment]
Hey @jcameron !

Being created. I'm migrating virtual servers from one server to another and its duplicating (or not overwriting) the entries for all dns entries except for SOA, keeping the first server and creating new entries for the second.

**Comment by iliajie** [comment]
I can also reproduce this problem, where DNS IP is not updated correctly. Also, using `Server Configuration ⇾ Change IP Address` page doesn't update it.

**Comment by abclution** [comment]
> I can also reproduce this problem, where DNS IP is not updated correctly. Also, using `Server Configuration ⇾ Change IP Address` page doesn't update it.

Oh thank fsck its not only me. Why  do I always run into show stopping bugs. lmao, just lucky I guess.

**Comment by jcameron** [comment]
Damn, I was able to confirm this bug :-(  Looking into it now ..

**Comment by jcameron** [comment]
Ok this should fix it : https://github.com/virtualmin/virtualmin-gpl/commit/18ee3b6ef0936146aafe93ad16b6f9019cb27e5d

**Comment by abclution** [comment]
Will test shortly

**Comment by iliajie** [comment]
> Ok this should fix it : [18ee3b6](https://github.com/virtualmin/virtualmin-gpl/commit/18ee3b6ef0936146aafe93ad16b6f9019cb27e5d)

Jamie, I'm pretty sure this patch won't fix it. Also, why DNSSEC records should not be taken from the backup?

**Comment by abclution** [comment]
Ok, at first glance this seems fixed for me. 

Ended running into another issue while doing server transfers left and right while debugging this issue, so am not 100% certain all is well yet.  ;)

Please see here:  https://github.com/virtualmin/virtualmin-gpl/issues/493

**Comment by iliajie** [comment]
> Ok, at first glance this seems fixed for me.

What do you mean by "at first glance"? Does it fix the original issue that you have reported earlier or not? Could you please provide a screenshot of how the records looked for you before and after this patch?

Jamie, do we intentionally keep local IPs (like `10.x.x.x` and `192.168.x.x`) in SPF record _not updated_? Base IP is getting updated as expected though.

> Jamie, I'm pretty sure this patch won't fix it.

Unless, the issue was related to DNSSEC records only?

**Comment by abclution** [comment]
> What do you mean by "at first glance"? Does it fix the original issue that you have reported earlier or not? Could you please provide a screenshot of how the records looked for you before and after this patch?

At first glance meaning until I hit that other mentioned bug (its relevant only as much as I am testing this fix via the server transfer feature) and had to figure out what was causing it, the first restore/transfer looked ok. 

I  am currently cleaning up a mess of orphaned groups from https://github.com/virtualmin/virtualmin-gpl/issues/493 and I noticed a possible issue with this fix ( https://github.com/virtualmin/virtualmin-gpl/commit/18ee3b6ef0936146aafe93ad16b6f9019cb27e5d ) but as I am in the middle of something else will take me a bit more time to validate my findings. Working on it!

**Comment by jcameron** [comment]
> Also, why DNSSEC records should not be taken from the backup?

Because they get re-generated after the restore.

**Comment by abclution** [comment]
> > Also, why DNSSEC records should not be taken from the backup?
> 
> Because they get re-generated after the restore.

Sorry this took me so long, I was encountering some sporadic undefined behavior which turned out I hadn't restarted webmin on  one of the servers between patches. Sigh. Like I said, I'm rusty with virtualmin atm.

So, back to the subject at hand, while the standard records are not duplicated anymore with this patch, the keys are not regenerated during the restore/transfer.
 
in DNS Options
![image](https://user-images.githubusercontent.com/10130237/209430458-885994b8-50a3-482b-bacf-e6ff65d346bb.png)

And webmin agrees in Bind that there is no DNSSEC key for the domain

![image](https://user-images.githubusercontent.com/10130237/209430772-23837785-36d1-4f6a-82d0-0c7260bc9d2c.png)

Resetting the feature on the domain does fix the DS records and DNSKEY record.

**Comment by iliajie** [comment]
Jamie, you seem to skip DNSSEC records for the domain upon restore but never regenerated it later?

Also, the records supposed to be regenerated using the same DS record .. it's possible right?

**Comment by jcameron** [comment]
Seems like we're missing something here on the restore - looking into it now.

**Comment by jcameron** [comment]
Ok this will fix that DNSKEY record issue : https://github.com/virtualmin/virtualmin-gpl/commit/4588a41cc7b7f4ff2c8d7ccafddcfd98b9fbbca2

**Comment by abclution** [comment]
> Ok this will fix that DNSKEY record issue : [4588a41](https://github.com/virtualmin/virtualmin-gpl/commit/4588a41cc7b7f4ff2c8d7ccafddcfd98b9fbbca2)

This seems ok now. Will continue to test.

**Comment by abclution** [comment]
Sorry I was incorrect, most recent patch fixed the DNSSEC key but the original issue appeared again. 

Its duplicating again.

**Comment by abclution** [comment]
I'm a monkey with a hammer with PERL but it appears the corrected fix is to replace the line with this.

` next if ($r->{'type'} ne 'DNSKEY' && &is_dnssec_record($r));`

**Comment by abclution** [comment]
Please ignore/close the pull request, I wrongly though it had stopped duplicated with my fix but it had showed me the records for another domain that moment confusing me.

**Comment by abclution** [comment]
```
# With this, records properly created (not duplicated) DNSSECKEY restore broken.
               next if ($r->{'type'} eq 'DNSKEY');

# With this, records properly created (not duplicated) DNSSECKEY restore broken. same as above, wat
               next if (&is_dnssec_record($r));

# With nothing here, DNSSEC key is not working and the entries are duplicated.

# With this, records are not created, DNSSECKEY does work.
               next if ($r->{'type'} ne 'DNSKEY');
```

**Comment by jcameron** [comment]
OK, so it's all good now?

**Comment by abclution** [comment]
Sorry, no it is not, 

With your most recent patch https://github.com/virtualmin/virtualmin-gpl/commit/4588a41cc7b7f4ff2c8d7ccafddcfd98b9fbbca2  it began duplicating again but DNSSEC keys are ok.

I tried to solve it myself but I could not, I though I did but I was mistaken.

**Comment by abclution** [comment]
From what I can understand, the code thinks that all dnssec_records are type DNSKEY records and vice versa.

These two lines should not produce the same results on a restore, but they do. :/

`               next if ($r->{'type'} eq 'DNSKEY');
`
`               next if (&is_dnssec_record($r));
`

**Comment by iliajie** [comment]
Is there a way you could email me the link for your backup (ilia at virtualmin dot com)? It would help a lot. I know I said that I could reproduce the problem, but I actually didn't (it was something else).

**Comment by abclution** [comment]
@iliajie Sent.

**Comment by iliajie** [comment]
I didn't get anything. Try `support+github-issue-491 at ilia dot engineer` email.

**Comment by abclution** [comment]
@iliajie Sent again.

**Comment by abclution** [comment]
Just a sec, got a bounce this time. It didn't like the bz2 file. just a sec

**Comment by iliajie** [comment]
I have taken a closer look using your backup files but I don't see records being duplicated .. However, I noticed that after restoring your domain I can see an error in DNSSEC Setup Key page in Webmin:

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/4426533/209668778-b3581053-f8c0-49f9-a54a-10c3704b8395.png">

I remember "fixing" this problem in one of the PRs in the past.

---

After taking a deeper look, I think I have found a bug, as the real simplest solution to this problem is just to regenerate DNSSEC records (of course using old DS key). Please try this patch (from PR). It should solve your problem https://github.com/virtualmin/virtualmin-gpl/pull/494/files.

**Comment by iliajie** [comment]
@abclution Also, can you tell us exactly, how did you make that backup you shared with me over the email? Did you use Virtualmin CLI (if so, please post the exact command) or you used the UI?

**Comment by abclution** [comment]
@iliajie UI

**Comment by abclution** [comment]
I belive I did it exactly as show in this screenshot, I know I dont need to press the select all button (when backup all features is selected, but its a force of habit. 

![image](https://user-images.githubusercontent.com/10130237/209686508-f8de2520-0fe3-4079-9963-2f9d4586fd6c.png)

**Comment by iliajie** [comment]
I am just very confused as running tests. What I cannot understand yet is when I use your backup, DS record always stays the same after restore. When I make a new backup with one of my local domains, with DNSSEC enabled, and then restore it, then DS key always happen to be different.

**Comment by abclution** [comment]
... have we found the ghost in the machine?

**Comment by iliajie** [comment]
.. something causes `my @keys = &bind8::get_dnssec_key(&get_bind_zone($d->{'dom'}));` not return keys ..

**Comment by iliajie** [comment]
.. oh, you also have `Create DNSSEC key and sign new domains` enabled on the templates .. so it pre-creates records and then works with my patch as expected .. but there is more to fix .. not sure yet what's wrong ..

**Comment by iliajie** [comment]
Alright, I got what the problem was, and the latest commit on the [PR](https://github.com/virtualmin/virtualmin-gpl/pull/494/files) fixes it for all modes.

It works flawlessly for me, although, I am not sure, if Jamie wouldn't want to come with a different solution.

But restoring DNSSEC now works correctly with this PR and DS key is always preserved.

**Comment by jcameron** [comment]
There's something deeper going on here that I need to fix ... it's not really related to DNSSEC at all.

**Comment by iliajie** [comment]
But we have a problem with DNSSEC restore.

**Comment by jcameron** [comment]
That was just the trigger - the proper fix, in my opinion, is here : https://github.com/virtualmin/virtualmin-gpl/commit/45318b4d1421afe1cc6db535a5c175838140d56a

**Comment by iliajie** [comment]
Will that regenerate DNSSEC records?

**Comment by iliajie** [comment]
Okay, I see the fix now. It must solve the problem with IPs not being updated, right? But what about DNSSEC bug which I clearly described?

**Comment by iliajie** [comment]
Gave it a quick test and this patch expectedly won't fix DNSSEC restore issue. My PR will.

**Comment by jcameron** [comment]
Can you explain in more detail what's going wrong with the DNSSEC records?  With the latest code, I was able to create a domain, back it up, check the DS records, delete it, restore and then check the DS records again. And they were the same.

**Comment by abclution** [comment]
> That was just the trigger - the proper fix, in my opinion, is here : [45318b4](https://github.com/virtualmin/virtualmin-gpl/commit/45318b4d1421afe1cc6db535a5c175838140d56a)

I just tested this and at first glance fixed the duplicated records and missing DNSKEY situation.  aka both issues. Will do additional testing shortly.

Am going to test @iliajie patch as well.

**Comment by abclution** [comment]
> That was just the trigger - the proper fix, in my opinion, is here : [45318b4](https://github.com/virtualmin/virtualmin-gpl/commit/45318b4d1421afe1cc6db535a5c175838140d56a)

Created domain on server1 transferred to server2 & transferred back for good measure. All is well.
DNS Records OK, no duplication.
DNSKEY/DS Records OK, Preserved keys + DS records on transfer

![image](https://user-images.githubusercontent.com/10130237/209783052-b6be5b32-d48c-4f5b-9016-620c308edc08.png)

Have a few more checks in mind but so far looks good. Onward to Ilias patch

**Comment by abclution** [comment]
> Alright, I got what the problem was, and the latest commit on the [PR](https://github.com/virtualmin/virtualmin-gpl/pull/494/files) fixes it for all modes.
> 
> It works flawlessly for me, although, I am not sure, if Jamie wouldn't want to come with a different solution.
> 
> But restoring DNSSEC now works correctly with this PR and DS key is always preserved.

@iliajie  Just tested your PR while the DNSSEC/DS records are preserved, I'm still getting duplication of records. I belive you are not seeing that because you are (presumably?) testing backup and restore on a single server, while I am transferring from one server to another. The duplicated records are not clones, just duplicated entries for example ftp.*  with the prior server IPs & and new server IPs. On the same server, the records are not duplicated

example.  
(Server 1, originating server, 188.40.x.x / 2a01:4f8:X:X:X:X)
(Server 2, destination server, 95.217.x.x / 2a01:4f9:X:X:X:X)
Image from the restored DNS records on Server 2
![image](https://user-images.githubusercontent.com/10130237/209785378-05de782c-902b-4006-9227-441027638090.png)

**Comment by iliajie** [comment]
> With the latest code, I was able to create a domain, back it up, check the DS records, delete it, restore and then check the DS records again.

Negative. This cannot be! You are probably just checking for `dsset-dom.com.` file. That file is irrelevant, because the moment you turn DNSSEC off and on, it will be regenerated from a newly generated (not from restored) public key (as a DS record is only a hash of public DNSKEY record) which again _wasn't restored_, and will result into a different DS record.

> Can you explain in more detail what's going wrong with the DNSSEC records?

Yes, most definitely!

   **1.** If you restore a domain with default template (when DNSSEC is not enabled by default), then DNSSEC private and public keys from the backup won't be restores simply because `@keys = &bind8::get_dnssec_key(&get_bind_zone($d->{'dom'}));` will always return _empty_! This will result into different DS record and additional pain for domain owner, to change it on the registrar side. This particular code from my [PR solves this](https://github.com/virtualmin/virtualmin-gpl/pull/494/files#diff-593862192870a07a479b57802409a1ff184bb342b4d3056be4861880d1194aa8R2405-R2414).
    **1.1.** The second case scenario is when a template have DNSSEC enabled by default (in case of @abclution), which will generate at first the random pair of public and private keys. Later, upon the actual restore earlier mentioned `@keys` will return data, and the code right below, with `_dnssec_keyinfo` that actually restores public and private keys from the backup _**will work**_, resulting in having correct keys restored for the domain. That means, if you disable and then re-enable DNSSEC for the domain it will actually work (has expected DS record).
  **2.** Nevertheless, we still need to toggle DNSSEC for the domain to regenerate the fresh records. Otherwise, considering the [latest code](https://github.com/virtualmin/virtualmin-gpl/commit/4588a41cc7b7f4ff2c8d7ccafddcfd98b9fbbca2#diff-593862192870a07a479b57802409a1ff184bb342b4d3056be4861880d1194aa8R2399) that Jamie committed a few days ago, the zone will only have DNSKEY record after the restore, which is invalid. It will though show that DNSSEC  is enabled simply because `has_domain_dnssec` is looking for DNSKEY record and finds it. This particular code from my [PR solves this](https://github.com/virtualmin/virtualmin-gpl/pull/494/files#diff-593862192870a07a479b57802409a1ff184bb342b4d3056be4861880d1194aa8R2517-R2522).
  
 
 > Just tested your PR while the DNSSEC/DS records are preserved, I'm still getting duplication of records.
 
 This is impossible because it's regenerated afterwards. Make sure that you update the file in whole, [using this link](https://raw.githubusercontent.com/virtualmin/virtualmin-gpl/2b223184d7d89ffa415527c71843e63a7fbdcb58/feature-dns.pl).
 
 > testing backup and restore on a single server, while I am transferring from one server to another.
 
 No, I'm using different servers. Although, there is still a separate bug which doesn't update SPF local IP correctly.
 
 > The duplicated records are not clones, just duplicated entries for example ftp.* with the prior server IPs & and new server IPs.
 
 Yeah, that should be fixed in Jamie's latest patch, which is already included in my PR.
 
 Give it a try and pay attention to the actual DNSSEC records and `dsset-dom.com.` file not just after the restore but also after turning DNSSEC off and on again.
 
 Here is the example backup which you could also use to try, with and without my PR, and see that in described case **1.** it will never return `5A8B` DS record after toggling DNSSEC off/on. And case **2.** you case, it will still work after DNSSEC toggling but not before (the zone will miss a lot of records).

**Comment by abclution** [comment]
Sure, will try it again.  I did replace the whole file previously but will try again as well as 

>after turning DNSSEC off and on again.

which I did NOT do previously.

**Comment by abclution** [comment]
Sorry @iliajie you mentioned

> Otherwise, considering the [latest code](https://github.com/virtualmin/virtualmin-gpl/commit/4588a41cc7b7f4ff2c8d7ccafddcfd98b9fbbca2#diff-593862192870a07a479b57802409a1ff184bb342b4d3056be4861880d1194aa8R2399) that Jamie committed a few days ago,

But the code I tested from him is this one. Just FYI
https://github.com/virtualmin/virtualmin-gpl/commit/45318b4d1421afe1cc6db535a5c175838140d56a

**Comment by iliajie** [comment]
> But the code I tested from him is this one. Just FYI
> [45318b4](https://github.com/virtualmin/virtualmin-gpl/commit/45318b4d1421afe1cc6db535a5c175838140d56a)

Yes, correct. This patch also includes what I referred to https://github.com/virtualmin/virtualmin-gpl/blob/45318b4d1421afe1cc6db535a5c175838140d56a/feature-dns.pl#L2399.

**Comment by abclution** [comment]
@iliajie Unfortunately I still have the duplication issue with your code :( Didn't even get the check the DNSSEC key issue

On both my servers, 

` mv feature-dns.pl feature-dns.pl.JAMIE; wget https://raw.githubusercontent.com/virtualmin/virtualmin-gpl/2b223184d7d89ffa415527c71843e63a7fbdcb58/feature-dns.pl; service webmin restart`


Transfer the virtual-server, check DNS, they are all duplicated again.

![image](https://user-images.githubusercontent.com/10130237/209812600-e0b4f805-09ca-4d10-8e61-2cc5c7c6ccd4.png)
 

Don't know what to say.

**Comment by iliajie** [comment]
> Unfortunately I still have the duplication issue with your code :( Didn't even get to check on the DNSSEC key issue

And which file did you use exacty?

**Comment by abclution** [comment]
> > Unfortunately I still have the duplication issue with your code :( Didn't even get to check on the DNSSEC key issue
> 
> And which file did you use exactly?

Created a new domain on server1, transferred it to server2.

**Comment by iliajie** [comment]
Looking into it ...

**Comment by iliajie** [comment]
> Unfortunately I still have the duplication issue with your code :( Didn't even get to check on the DNSSEC key issue
> 
> On both my servers,
> 
> ` mv feature-dns.pl feature-dns.pl.JAMIE; wget https://raw.githubusercontent.com/virtualmin/virtualmin-gpl/2b223184d7d89ffa415527c71843e63a7fbdcb58/feature-dns.pl; service webmin restart`

Ah, I see the problem now. The [fix is here](https://github.com/virtualmin/virtualmin-gpl/pull/494/commits/0ee1ce8292b424365f44366000ecfa326b42b750). Unfortunately, `get_bind_zone` cannot return the structure for non existent records. Otherwise this code-block wouldn't be needed at all, and we could just re-sync DNSSEC records in the end of DNS restore..

**Comment by abclution** [comment]
@iliajie Great news, works as expected. No time right this moment to review the DNSSEC stuff but at first glance looks OK as well. Will update if something changes. :)

**Comment by iliajie** [comment]
Thanks, I know it works, thanks.

@jcameron Jamie, here is [much better solution](https://github.com/virtualmin/virtualmin-gpl/pull/494/files) code-wise to the problem, and a safer one too! It will also print clear output:

<img width="345" alt="image" src="https://user-images.githubusercontent.com/4426533/209829286-b450e12a-d447-417e-afeb-c57b75dbce0f.png">

Well tested. Have a look. If you have any questions we can talk in a call.

**Comment by jcameron** [comment]
> 1. If you restore a domain with default template (when DNSSEC is not enabled by default), then DNSSEC private and public keys from the backup won't be restores

Ah I see what you mean. This simple fix should solve it : https://github.com/virtualmin/virtualmin-gpl/commit/61b1a3d90a65bd52f9478becdd77e425083526f8

> 2. Nevertheless, we still need to toggle DNSSEC for the domain to regenerate the fresh records. 

Which records are you referring to in this case?

**Comment by iliajie** [comment]
> Ah I see what you mean. This simple fix should solve it : [61b1a3d](https://github.com/virtualmin/virtualmin-gpl/commit/61b1a3d90a65bd52f9478becdd77e425083526f8)

Looks good to me. I will test it over again though.



> Which records are you referring to in this case?

DNSSEC records, we need to refresh them, right? Because right now, we only have `IN DNSKEY` records on the zone after restore. We need to resign the zone properly..

**Comment by iliajie** [comment]
> https://github.com/virtualmin/virtualmin-gpl/commit/61b1a3d90a65bd52f9478becdd77e425083526f8 Yes this is close to what I did in my PR. Although, enabling DNSSEC before restoring stored public and private keys is incorrect. 

Alright, ran tests. It won't work (has a wrong DS record), because if you enable DNSSEC first and only then restore the public and private keys the zone won't have the right signature. It will require to resign the zone to have the expected DS record!

Jamie, can you please just review my PR one more time? I have spent considerable amount of time making it right and running tests to make sure that it actually works! What is the point for me to create and test PRs, if it's not being used after all? We need to go with a new release..

**Comment by abclution** [comment]
Still something funky going on.. sometimes, the SOA is wrong on restore and has the old servers SOA resetting the dns feature does NOT fix this, not sure why, exhausted at the moment will go into it a bit more tomorrow if I can figure out more.

**Comment by abclution** [comment]
Guys, I'm still getting some other massive restore failures in regards to DNS records, seems to be related to alias domains and the server template option "Add sub-domain DNS records to parent domain = No"

Its so effed up I dont know how to explain it fully, nor do I know wether to create a new issue for this or whatever.. Lol. Let me try to break it off into bite sized chunks.

So first off, I have a backup of an some alias subdomains with only DNS + email enabled. 

In its server template 
"Add sub-domain DNS records to parent domain = No" so that it keeps its records in its own bind file.
When I restore this subdomain, all hell breaks loose in the records. Like seriously. 

A simple example is I add a few custom bind records 
ex cdn. which should create for example a record that looks like this: 

```
cdn1.subdomain-1.thisdomain.com.	IN	CNAME	www.subdomain-1.thisdomain.com.
cdn2.subdomain-1.thisdomain.com.	IN	CNAME	www.subdomain-1.thisdomain.com.
cdn3.subdomain-1.thisdomain.com.	IN	CNAME	www.subdomain-1.thisdomain.com.
```

But on restore, its doing something like this

```
cdn1.subdomain-1.thisdomain.com.	IN	CNAME	www.subdomain-1.subdomain-2.subdomain-3.subdomain-4.thisdomain.com.
cdn2.subdomain-1.thisdomain.com.	IN	CNAME	www.subdomain-1.subdomain-2.subdomain-3.subdomain-4.thisdomain.com.
cdn3.subdomain-1.thisdomain.com.	IN	CNAME	www.subdomain-1.subdomain-2.subdomain-3.subdomain-4.thisdomain.com.
```
Its somehow parsing the additional alias subdomains attached to this domain and inserting them willy nilly..


But wait, there's more.

If I delete and restore (from the same backup) lets say subdomain-1.thisdomain.com, inexplicably it will rewrite the records file correctly.... except and here is the real fucker.. if I try to also delete and restore subdomain-2.thisdomain.com backup, it will trash (like above) both the 

subdomain-2.thisdomain.com.hosts file, AND trash the subdomain-1.thisdomain.com.hosts file.

Its total madness.

**Comment by jcameron** [comment]
@abclution that's a nasty bug! But it sounds like a separate issue from the DNSSEC problem you originally reported..

Could I ask you to open a separate ticket for this? It will make tracking the fix easier..

**Comment by abclution** [comment]
Ok, I'm  gonna mark this, the primary issue, as closed and fixed as of Virtualmin 7.5 release.
