### ISSUE TITLE
You can only add DNS records to the Parent's zone upon Sub-Server creation

### ISSUE THREAD

**Issue by shoulders** [virtualmin/virtualmin-gpl#700]
|  SYSTEM INFORMATION||
|----------------------|---------------------------|
|  OS type and version |     Ubuntu Linux 22.04.3     |
|  Webmin version      |     2.105      |
|  Usermin version     |     2.005     |
|  Virtualmin version  |     7.8.2       |
|  Theme version       |     21.09.5      |
|  Package updates     |      37  package updates are available, of which  5  are security updates   |

I don't know if this is classed as a bug or a feature request:

## The Setup
I have a parent domain called **quantumwarp.com** and it has some sub-servers with the domains **wordpress.quantumwarp.com** and **themes.quantumwarp.com**.

The parent domain does have DNSSEC enabled.

I am not sure which one, or if both were top-level servers which i then converted/moved to **quantumwarp.com** as sub-servers.

- **themes.quantumwarp.com**
  - has it's DNS records in the parents DNS zone
  - does **NOT** have a DNS Options Menu.
  - does have a DNS Records menu
- **wordpress.example.com**
  - does **NOT** have has it's DNS records in the parents DNS zone
  - it has a DNS Options Menu.
  - it has a DNS Records menu
 
## The Issue
I want to move my DNS records for **wordpress.example.com** into the parent's zone file.

### Enable/Disable `DNS domain` in `Edit Virtual Server`
![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/e72ca2f2-01b1-4b74-9459-ae5fbca1840e)

- `Default Server` template --> DNS Options --> Add sub-domain DNS records to parent domain: Yes
- `Settings For Sub-Servers` template --> DNS Options --> Add sub-domain DNS records to parent domain: Yes
- Then i went to **wordpress.quantumwarp.com** --> Edit Virtual Server
- Disabled 'DNS domain enabled'
- saved
- straight way I went back and re-enabled the DNS.

Now I assumed the DNS records would be added in the parent server's zone file, they were not and stayed in their own file in  `/var/lib/bind`.

### Move the virtual server
I thought that moving the virtual server would allow the use of the `Add sub-domain DNS records to parent domain` option when the enable/disable above did not work.

- I moved the wordpress sub-server and it made no difference. The DNS Zone had its own file in `/var/lib/bind`
- I moved the themes sub-server  (which had its DNS records in it's parent DNS zone file) and it's DNS records were hived off into a separate file.

## I have not tried
I am not really sure what this is.
Webmin --> Servers --> BIND DNS Server --> Convert to Slave Zone

## Conclusion
You can only ever add a sub-servers DNS records to the parents records file at the point of creation.

**Comment by jcameron** [comment]
Do all these domains in Virtualmin have the same owner? By default, sharing of DNS records in the same zone file only works if they are under the same user.

**Comment by shoulders** [comment]
- yes they all have the same owner, there is the one parent and then 2 sub-servers
- to double check, they all have the same `administration username`

**Comment by jcameron** [comment]
Can you post the output you get when you disable and then re-enable the DNS feature for the sub-domain?

Also, in that screenshot, why is the domain quantumwarp.com not listed?

**Comment by shoulders** [comment]
>  in that screenshot, why is the domain quantumwarp.com not listed?

This is because i used: `Virtualmin (quantumwarp.com)  --> Administration Options --> List Sub-Servers`

### wordpress.quantumwarp.com - Edit Virtual Server --> DNS domain enabled: ticked to unticked

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/eab451b5-972b-43b0-b6f3-e7e7533c6fda)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/eaf3d0e1-7a7b-4251-aba9-9df169dfbaa0)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/8eb06c25-676b-49b5-b6e0-95ff29e4a02f)

### wordpress.quantumwarp.com - Edit Virtual Server --> DNS domain enabled: unticked to ticked

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/8ce9a7a4-9ae5-461d-ac95-1c1be3f8694d)

![image](https://github.com/virtualmin/virtualmin-gpl/assets/319997/fe3b6b05-b817-4071-8432-534325e6a48a)

**Comment by jcameron** [comment]
Hmm, that is quite confusing! I assume that the DNS feature is enabled on the quantumwarp.com domain?

**Comment by jcameron** [comment]
So what should happen is when DNS is disabled and re-enabled, if the template option to use the parent domain's zone file is enabled, it will be respected - even if it wasn't before. 

Is this feature enabled in the sub-server template on your system?

**Comment by jcameron** [comment]
Ok I think I see the issue better now. When you say "When you move a server, this flag is either deleted or set to use separate zone files", does moving meaning changing the domain to a new owner? Or turning it from a sub-server to a server with it's own user?

**Comment by shoulders** [comment]
## what happen for me (the bug)

- I moved a sub-server from one owner to another, and the DNS records were removed from the old parent but were not installed into the new parent's dns zone but had it's own zone file created

## What should happen if the `Add sub-domain DNS records to parent domain` flag is set on the target
- if you move a top-level server to be a sub-server of another account, then the records should be put in the target parent's DNS zone
- if you move a sub-server to be under another owner, then the records should be put in the targets parent's DNS zone, irrespective of where they were before.
- when you enable/disable the DNS on a virtual server, this flag should be read and the records put in the parent

**Comment by shoulders** [comment]
- quantumwarp.com
  - themes.quantumwarp.com (DNS records in the parent)

-->

- example.com
  - themes.quantumwarp.com (DNS records in a separate zone file)

-->

- quantumwarp.com
  - themes.quantumwarp.com (DNS records in a separate zone file)

**Comment by jcameron** [comment]
Ah, so the real issue is that when a domain is renamed and the records are now eligible to be included in the parent's zone, they are not moved over. I'll look into a fix for that, and update this ticket when it's done.

**Comment by jcameron** [comment]
Ok, this will be fixed in the upcoming 7.9.0 Virtualmin release

**Comment by shoulders** [comment]
@jcameron

Did this get fixed in 7.9.0? I can't get it to work.

can you confirm that the following would put all of the DNS records in one zone if the server template is configured for this
- DNS On/Off
- Moving he virtual server

Thanks

**Comment by jcameron** [comment]
Yes, it should be fixed in 7.9.0. If it's not working for you still, please let me know the exact steps that aren't working...

**Comment by shoulders** [comment]
Not forgot this, I will double check and report my results.

**Comment by shoulders** [comment]
I have just checked and the following does not change change the DNS back to parent:

> themes.quantumwarp.com (sub-server)
Add sub-domain DNS records to parent domain = from default settings = yes

- Move themes sub-server : quantumwarp.com --> svchost.uk
- Move themes sub-server: svchost.uk --> quantumwarp.com

In the DNS record for quantumwarp.com the following record are still present also showing nothing changed.
```
themes.quantumwarp.com.	IN	DS	
themes.quantumwarp.com.	IN	NS	ns1.svchost.uk.
```

**Comment by jcameron** [comment]
So do quantumwarp.com and svchost.uk have different owners? And did you rename themes.quantumwarp.com to themes.svchost.uk ?

**Comment by shoulders** [comment]
- `quantumwarp.com` and `svchost.uk` are both parent/top-level accounts with different usernames.
- actions
  1. I moved the sub-server `themes.quantumwarp.com (sub-server)` from `quantumwarp.com (top level server)` to `svchost.uk (top level server)`. I did not rename it.
  2. I then moved  `themes.quantumwarp.com (sub-server)` back to `quantumwarp.com (top level server)` . I did not rename it

**Comment by jcameron** [comment]
Ok ... in the current code, a change of ownership like that won't trigger moving the DNS records into the new parent's zone file. However, you can do this with a separate API command like :

`virtualmin modify-dns --domain themes.quantumwarp.com  --enable-subdomain`

**Comment by shoulders** [comment]
@jcameron 
- thanks for the workaround
- will this issue get reopened and fixed?

**Comment by jcameron** [comment]
Since we have a work-around, I'm not sure that we really need to automatically do the records move when ownership changes..

**Comment by shoulders** [comment]
- Virtualmin is so we don't have to use the command line for normal operations
- Consistency:
  - Whenever you move a subdomain, it will be removed from a parent and can never be added back into a parent even if allowed, using the GUI.
  - If you have this feature to move domains about in Virtualmin it should work properly. I would class this as a bug rather than a feature, and as an end user I would expect the move to obey what is defined in the `sub-server template`.
- Virtualmin is powerful, but it is the usability and mismatch of settings that I have found difficult. Hence all of the bug/feature reports.

hope this did not sound harsh :smile:

**Comment by jcameron** [comment]
Ok I'll take another look at handling the case you mentioned ...

**Comment by jcameron** [comment]
Turns out this was easy to fix! It will be solved in the next Virtualmin release ...
